config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('mascota/', include('mascota.urls')),
    path('adopcion/', include('adopcion.urls')),
    path('', include('core.urls')),
    path('accounts/', include('django.contrib.auth.urls')),  
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = "core"

urlpatterns = [
    path("", views.home, name="home"),
    path("login/", views.CustomLoginView.as_view(), name="login"), 
    path("logout/", LogoutView.as_view(template_name="core/logout.html"), name="logout"),
    path("register/", views.register, name="register"),
    path("edit_profile/", views.edit_profile, name="edit_profile"), 
    path('sobre-mi/', views.sobre_mi, name='sobre_mi'),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mascota/urls.py
from django.urls import path
from .views import *

app_name = 'mascota'

urlpatterns = [
    path('crear/', mascota_create, name='mascota_create'),
    path('lista/', mascota_list, name='lista_mascotas'),
    path('detalle/<int:pk>/', mascota_detail, name='detalle_mascota'),
    path('actualizar/<int:pk>/', mascota_update, name='actualizar_mascota'),
    path('eliminar/<int:pk>/', mascota_delete, name='mascota_confirm_delete'),
]

mascota/models.py
from django.db import models
from django.utils import timezone


class MascotaCategoria(models.Model):
    nombre = models.CharField(max_length=200, unique=True)
    descripcion = models.CharField(max_length=250, null=True, blank=True, verbose_name="descripción")

    def __str__(self) -> str:
        return self.nombre

    class Meta:
        verbose_name = "categoría de mascotas"
        verbose_name_plural = "categorías de mascotas"

class Mascota(models.Model):
    categoria_id = models.ForeignKey(
        MascotaCategoria, null=True, blank=True, on_delete=models.SET_NULL, verbose_name="categoría de mascota"
    )
    adoptada = models.BooleanField(default=False)
    nombre = models.CharField(max_length=100)
    especie = models.CharField(max_length=100)
    tamano = models.CharField(max_length=100)
    edad = models.IntegerField()
    descripcion = models.TextField(null=True, blank=True, verbose_name="descripción")
    fecha_actualizacion = models.DateField(
        null=True, blank=True, default=timezone.now, editable=False, verbose_name="fecha de actualización"
    )
    foto = models.ImageField(upload_to='mascotas/', null=True, blank=True, verbose_name="foto")

    def __str__(self) -> str:
        return self.nombre

    class Meta:
        verbose_name = "mascota"
        verbose_name_plural = "mascotas"

mascota/forms.py
from django import forms
from .models import Mascota
from . import models

class MascotaCategoriaForm(forms.ModelForm):
    class Meta:
        model = models.MascotaCategoria
        fields = "__all__"
        widgets = {
            "nombre": forms.TextInput(attrs={"class": "form-control"}),
            "descripcion": forms.TextInput(attrs={"class": "form-control"}),
        }

class MascotaForm(forms.ModelForm):
    class Meta:
        model = Mascota
        fields = "__all__"
        labels = {
            "tamano": "Tamaño"
        }
        widgets = {
            "nombre": forms.TextInput(attrs={"class": "form-control"}),
            "especie": forms.Select(attrs={"class": "form-control"}, choices=[('perro', 'Perro'), ('gato', 'Gato')]),
            "tamano": forms.Select(attrs={"class": "form-control"}, choices=[('chico', 'Chico'), ('mediano', 'Mediano'), ('grande', 'Grande')]),
            "edad": forms.NumberInput(attrs={"class": "form-control"}),
            "descripcion": forms.Textarea(attrs={"class": "form-control", "rows": 3}),
            "foto": forms.FileInput(attrs={"class": "form-control"}),
        }

mascota/views.py
from django.db.models.query import QuerySet
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView, ListView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Mascota
from .forms import MascotaForm

def home(request):
    return render(request, 'mascota/mascota_list.html')

@login_required
def mascota_create(request):
    if request.method == 'POST':
        form = MascotaForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect(reverse_lazy('mascota:lista_mascotas'))
    else:
        form = MascotaForm()
    return render(request, 'mascota/mascota_form.html', {'form': form})

@login_required
def mascota_list(request):
    nombre = request.GET.get('consulta', None)
    queryset = Mascota.objects.all()
    if nombre:
        queryset = queryset.filter(nombre__icontains=nombre)
    return render(request, 'mascota/mascota_list.html', {'mascotas': queryset})

@login_required
def mascota_detail(request, pk):
    mascota = get_object_or_404(Mascota, pk=pk)
    return render(request, 'mascota/detalle_mascota.html', {'mascota': mascota})

@login_required
def mascota_update(request, pk):
    mascota = get_object_or_404(Mascota, pk=pk)
    if request.method == 'POST':
        form = MascotaForm(request.POST, request.FILES, instance=mascota)  
        if form.is_valid():
            form.save()
            return redirect(reverse_lazy('mascota:detalle_mascota', kwargs={'pk': mascota.pk}))
    else:
        form = MascotaForm(instance=mascota)
    return render(request, 'mascota/actualizar_mascota.html', {'form': form})
    
@login_required
def mascota_delete(request, pk):
    mascota = get_object_or_404(Mascota, pk=pk)
    if request.method == 'POST':
        mascota.delete()
        return redirect(reverse_lazy('mascota:lista_mascotas'))
    return render(request, 'mascota/mascota_confirm_delete.html', {'mascota': mascota})

mascota/templates/mascota/actualizar_mascota.html
{% extends 'core/base.html' %}

{% block titulo %}
    {{ form.instance.nombre }}
{% endblock titulo %}

{% block contenido %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-lg-8">
            <div class="card shadow-lg">
                <div class="card-header bg-primary text-white text-center">
                    <h4>
                        {% if form.instance.pk %}
                            Editar Mascota
                        {% else %}
                            Crear Mascota
                        {% endif %}
                    </h4>
                </div>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <div class="text-center mt-4">
                            <button type="submit" class="btn btn-success">Guardar</button>
                        </div>
                    </form>
                </div>
            </div>
            <div class="text-center mt-4">
                <a href="{% url 'mascota:lista_mascotas' %}" class="btn btn-secondary">Volver al inicio de Mascotas</a>
            </div>
        </div>
    </div>
</div>
{% endblock contenido %}

mascota/templates/mascota/detalle_mascota.html
{% extends 'core/base.html' %}

{% block titulo %}
    {{ mascota.nombre }}
{% endblock titulo %}

{% block contenido %}
    <div class="container mt-4">
        <h1 class="text-center mb-4" style="color: #2c3e50;">Detalles de {{ mascota.nombre }}</h1>
        
        <div class="row">
            <div class="col-lg-6 mb-4">
                <div class="card shadow-lg p-4">
                    <h2 class="h4">Información de la Mascota</h2>
                    <dl class="row">
                        <dt class="col-sm-4">Nombre:</dt>
                        <dd class="col-sm-8">{{ mascota.nombre }}</dd>
                        <dt class="col-sm-4">Tamaño:</dt>
                        <dd class="col-sm-8">{{ mascota.tamano }}</dd>
                        <dt class="col-sm-4">Descripción:</dt>
                        <dd class="col-sm-8">{{ mascota.descripcion }}</dd>
                    </dl>
                </div>
            </div>

            <div class="col-lg-6 mb-4">
                <div class="card shadow-lg p-4">
                    <h2 class="h4">Imagen de {{ mascota.nombre }}</h2>
                    <!-- Mostrar la imagen de la mascota -->
                    {% if mascota.foto %}
                        <img src="{{ mascota.foto.url }}" class="img-fluid" alt="{{ mascota.nombre }}">
                    {% else %}
                        <p>No hay imagen disponible.</p>
                    {% endif %}
                </div>
            </div>
        </div>

        <section class="d-flex justify-content-between mt-4">
            <a href="{% url 'adopcion:adopcion_create' %}" class="btn btn-primary">Adoptar a {{ mascota.nombre }}</a>
            <a href="{% url 'mascota:lista_mascotas' %}" class="btn btn-secondary">Volver</a>
        </section>
    </div>
{% endblock contenido %}

mascota/templates/mascota/index.html
{% extends 'core/base.html' %}
{% block titulo %}
    App Mascotas
{% endblock titulo %}
{% block contenido %}
<div class="container my-5">
    <h3 class="pb-3 border-bottom">Categoría de mascotas</h3>
    <div class="d-grid gap-2 d-md-flex justify-content-md-start mb-4">
        <a class="btn btn-primary me-md-2" href="{% url 'mascota:mascotacategoria_create' %}" role="button">Crear Categorías de Mascotas</a>
        <a class="btn btn-outline-primary" href="{% url 'mascota:mascotacategoria_list' %}" role="button">Listar Categorías de Mascotas</a>
    </div>

    <h3 class="pb-3 border-bottom">Mascotas</h3>
    <div class="d-grid gap-2 d-md-flex justify-content-md-start mb-4">
        <a class="btn btn-success me-md-2" href="{% url 'mascota:mascota_create' %}" role="button">Adoptar mascota:/a>
        <a class="btn btn-outline-success" href="{% url 'mascota:mascota_list' %}" role="button">Listar Mascotas</a>
    </div>

    <div class="d-grid gap-2 d-md-flex justify-content-md-start mb-4">
        <a class="btn btn-secondary" href="{% url 'core:home' %}" role="button">Volver a Inicio</a>
    </div>
</div>

{% endblock contenido %}

mascota/templates/mascota/mascota_confirm_delete.html
{% extends 'core/base.html' %}

{% block titulo %}
    Borrar Mascota
{% endblock titulo %}

{% block contenido %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-lg-6">
            <div class="card shadow-lg">
                <div class="card-header bg-danger text-white text-center">
                    <h4>Confirmación de Eliminación</h4>
                </div>
                <div class="card-body text-center">
                    <p class="fs-5 fst-italic">
                        ¿Confirmas eliminar la mascota "{{ mascota.nombre }}"?
                    </p>
                    <form method="post">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger btn-lg">Confirmar Eliminación</button>
                    </form>
                </div>
                <div class="card-footer text-center">
                    <a href="{% url 'mascota:lista_mascotas' %}" class="btn btn-secondary">Volver al Inicio de Mascotas</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock contenido %}

mascota/templates/mascota/mascota_create.html
{% extends "core/base.html" %}
<style>
    ul {color:red;}
    li {color:blue;} 
</style>

{% block content %}
    {% if error %}
        <p style="color: blue; font-weight: bold"> ERROR: {{ error }}</p>
    {% endif %}
    <form method="post"> 
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Guardar</button>
    </form>
{% endblock content %}

mascota/templates/mascota/mascota_form.html
{% extends 'core/base.html' %}

{% block titulo %}
    Mascota: 
    {% if form.instance.pk %}
        Editar Mascota
    {% else %}
        Crear Mascota
    {% endif %}
{% endblock titulo %}

{% block contenido %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-lg-8">
            <div class="card shadow-lg">
                <div class="card-header bg-primary text-white text-center">
                    <h4>
                        {% if form.instance.pk %}
                            Editar Mascota
                        {% else %}
                            Crear Mascota
                        {% endif %}
                    </h4>
                </div>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <div class="text-center">
                            <button type="submit" class="btn btn-success mt-3">Guardar</button>
                            <a href="{% url 'mascota:lista_mascotas' %}" class="btn btn-secondary mt-3">Volver al inicio de Mascotas</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock contenido %}

mascota/templates/mascota/mascota_list.html
{% extends 'core/base.html' %}
{% load static %}

{% block titulo %}
Mascotas: lista de mascotas
{% endblock titulo %}
{% block contenido %}
<section class="container my-5">
    <section class="py-4">
        <form class="input-group mb-3" action="{% url 'mascota:lista_mascotas' %}" method="get">
            <input type="text" class="form-control" name="consulta" placeholder="Buscar..." aria-label="Buscar">
            <button class="btn btn-outline-secondary" type="submit" id="button-addon2">Buscar</button>
        </form>
    </section>

    {% if not mascotas %}
        <p>No tenemos mascotas en adopción actualmente! 🥳</p>
    {% else %}
        <div class="row">
            {% for mascota in mascotas %}
                <div class="col-md-4 mb-4">
                    <div class="card h-100 shadow-sm">
                        <div class="card-body d-flex flex-column">
                            <h5 class="card-title">{{ mascota.nombre }}</h5>
                            <p class="card-text">{{ mascota.descripcion|truncatewords:20 }}</p>
                            <div class="mt-auto">
                                <a href="{% url 'mascota:detalle_mascota' mascota.id %}" class="btn btn-info btn-sm me-1">Detalle</a>
                                {% if user.is_superuser %}
                                    <a href="{% url 'mascota:actualizar_mascota' mascota.id %}" class="btn btn-warning btn-sm me-1">Cambiar</a>
                                    <a href="{% url 'mascota:mascota_confirm_delete' mascota.id %}" class="btn btn-danger btn-sm">Borrar</a>
                                {% endif %}
                                
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% endif %}

    <section class="mt-4">
        <a class="btn btn-secondary" href="{% url 'core:home' %}" role="button">Volver al inicio</a>
    </section>
</section>
{% endblock contenido %}

mascota/templates/mascota/mascotacategoria_confirm_delete.html
{% extends 'core/base.html' %}

{% block titulo %}
    Mascotas: Borrar una Categoría de mascotas
{% endblock titulo %}

{% block contenido %}
    
    <p class="fs-5 fst-italic">¿Confirmas eliminar "{{ object.nombre }}"?</p>

    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Confirmar</button>
    </form>
    <div class="fs-3 pb-4">
        <a href="{% url 'mascota:home' %}">Volver al inicio de mascota</a>
    </div>

{% endblock contenido %}

mascota/templates/mascota/mascotacategoria_detail.html
{% extends 'core/base.html' %}
{% block titulo %}
    Mascotas: detalle de una categoría de mascota
{% endblock titulo %}

{% block contenido %}

    <ul>
        <li>Nombre: {{ object.nombre }}</li>
        <li>Descripción: {{ object.descripcion }}</li>
    </ul>

    <div class="fs-3 pb-4">
        <a href="{% url 'mascota:mascotacategoria_list' %}">Volver</a>
    </div>

{% endblock contenido %}

mascota/templates/mascota/mascotacategoria_form.html
{% extends 'core/base.html' %}

{% block titulo %}
    Mascota: 
    {% if form.instance.pk %}
        Editar
    {% else %}
        Crear
    {% endif %}
    Categoría de mascota
{% endblock titulo %}

{% block contenido %}
    
    <form method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <button type="submit" class="btn btn-primary">Guardar</button>
    </form>
    <div class="fs-3 pb-4">
        <a href="{% url 'mascota:home' %}">Volver al inicio de mascota</a>
    </div>

{% endblock contenido %}

mascota/templates/mascota/mascotacategoria_list.html
{% extends 'core/base.html' %}
{% block titulo %}
    Mascotas: Lista de categoría de mascotas
{% endblock titulo %}

{% block contenido %}

    <div class="py-lg-4 ">
        <form action="{% url 'mascota:mascotacategoria_list' %}" method="get">
            <input type="text" name="consulta" placeholder="Buscar...">
        </form>
    </div>
    <ul>
        {% comment  %}
        {% for mascota in mascotas %}
        {% endcomment %}

        {% for mascota in object_list %}
            <li>{{ mascota.nombre }}
                <a href="{% url 'mascota:mascotacategoria_detail' mascota.id %}">Detalle</a>
                <a href="{% url 'mascota:mascotacategoria_update' mascota.id %}">Cambiar</a>
                <a href="{% url 'mascota:mascotacategoria_delete' mascota.id %}">Borrar</a>
            </li>
        {% endfor %}
    </ul>

    <div class="fs-3 pb-4">
        <a href="{% url 'mascota:home' %}">Volver al inicio de mascota</a>
    </div>

{% endblock contenido %}

mascota/templates/mascota/mascotacategoria_update.html
{% extends 'core/base.html' %}

{% block titulo %}
    Mascota: Cambiar una categoría de mascota
{% endblock titulo %}

{% block contenido %}
    
    <form method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <button type="submit" class="btn btn-primary">Guardar</button>
    </form>
    <div class="fs-3 pb-4">
        <a href="{% url 'mascota:mascotacategoria_list' %}">Volver</a>
    </div>

{% endblock contenido %}