config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('mascota/', include('mascota.urls')),
    path('adopcion/', include('adopcion.urls')),
    path('', include('core.urls')),
    path('accounts/', include('django.contrib.auth.urls')),  
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = "core"

urlpatterns = [
    path("", views.home, name="home"),
    path("login/", views.CustomLoginView.as_view(), name="login"), 
    path("logout/", LogoutView.as_view(template_name="core/logout.html"), name="logout"),
    path("register/", views.register, name="register"),
    path("edit_profile/", views.edit_profile, name="edit_profile"), 
    path('sobre-mi/', views.sobre_mi, name='sobre_mi'),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mascota/urls.py
from django.urls import path
from .views import *

app_name = 'mascota'

urlpatterns = [
    path('crear/', mascota_create, name='mascota_create'),
    path('lista/', mascota_list, name='lista_mascotas'),
    path('detalle/<int:pk>/', mascota_detail, name='detalle_mascota'),
    path('actualizar/<int:pk>/', mascota_update, name='actualizar_mascota'),
    path('eliminar/<int:pk>/', mascota_delete, name='mascota_confirm_delete'),
]

core/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, Group, Permission

class Usuario(AbstractUser):
    profile_pic = models.ImageField(upload_to='profile_pics/', blank=True, null=True)
    groups = models.ManyToManyField(Group, related_name='custom_user_set')
    user_permissions = models.ManyToManyField(Permission, related_name='custom_user_set_permissions')

core/forms.py
from django  import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from .models import Usuario

class CustomAuthenticationForm(AuthenticationForm):
    class Meta:
        model = Usuario
        fields = ["username", "password"]
        widget = {
            "username": forms.TextInput(attrs={"class": "form-control"}),
            "password": forms.PasswordInput(attrs={"class": "form-control"}),
        }

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = Usuario
        fields = ['username', 'password1', 'password2', 'profile_pic']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'password1': forms.PasswordInput(attrs={'class': 'form-control'}),
            'password2': forms.PasswordInput(attrs={'class': 'form-control'}),
            'profile_pic': forms.FileInput(attrs={'class': 'form-control'}),
        }
class CustomUserChangeForm(UserChangeForm):
    password = None
    class Meta:
        model = Usuario
        fields = ['username', 'profile_pic']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'profile_pic': forms.FileInput(attrs={'class': 'form-control'}),
        }

core/views.py
from django.shortcuts import render
from django.contrib.auth.views import LoginView
from django.contrib.auth.decorators import login_required
from .forms import CustomAuthenticationForm, CustomUserCreationForm, CustomUserChangeForm
from django.urls import reverse_lazy
from .models import Usuario
from django.shortcuts import render, redirect
from django.contrib import messages
from .forms import CustomUserCreationForm 


def home(request):
    return render(request, 'core/index.html')



def sobre_mi(request):
    return render(request, 'core/sobre_mi.html')


def register(request):
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save()
            messages.success(request, "Usuario creado exitosamente.")
            print("Profile picture:", user.profile_pic)  
            return redirect('core:home')
    else:
        form = CustomUserCreationForm()
    return render(request, 'core/register.html', {'form': form})


class CustomLoginView(LoginView):
    authentication_form = CustomAuthenticationForm
    template_name = "core/login.html"

    def get_success_url(self):
        return reverse_lazy('core:home')


@login_required
def edit_profile(request):
    if request.method == "POST":
        form = CustomUserChangeForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            messages.success(request, "Perfil actualizado correctamente!")
            return redirect('core:home')
    else:
        form = CustomUserChangeForm(instance=request.user)
        
    return render(request, 'core/edit_profile.html', {'form': form})

core/templates/core/components/card.html
<div class="col-md-4 mb-5">
    <div class="card h-100">
        <div class="card-body">
            <h2 class="card-title">{{ titulo }}</h2>
            <p class="card-text">{{ texto }}</p>
        </div>
        <div class="card-footer">
            <a class="btn btn-primary btn-sm" href="#!">Más info</a>
        </div>
    </div>
</div>

core/templates/core/components/footer.html
<footer class="py-2 bg-dark fixed-bottom">
    <div class="container px-4 px-lg-5">
        <p class="m-0 text-center text-white">Mascotapp, todas las patitas reservadas</p>
    </div>
</footer>

core/templates/core/components/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container px-5">
        <a class="navbar-brand" href="{% url 'core:home' %}"><img src="{% static "core/img/logo.webp.png" %}" alt="Mascotapp"></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item"><a class="nav-link {% if request.path == "/" %} active {% endif %}" aria-current="page" href="{% url 'core:home' %}">Inicio</a></li>
                <li class="nav-item"><a class="nav-link {% if request.path == "/about" %} active {% endif %}" href="{% url 'core:sobre_mi' %}">Nosotros</a></li>
                {% if user.is_authenticated %}
                    <li class="nav-item"><a class="nav-link {% if request.path == "/mascota/lista/" %} active {% endif %}" href="{% url 'mascota:lista_mascotas' %}">Mascotas</a></li>
                    <li class="nav-item"><a class="nav-link {% if request.path == "/adopcion/" %} active {% endif %}" href="{% url 'adopcion:adopcion_list' %}">Adoptados</a></li>
                    
                    <!-- Profile Dropdown -->
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle text-capitalize" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            {% if user.profile_pic %}
                                <img src="{{ user.profile_pic.url }}" alt="Profile Pic" class="profile-pic" style="width: 30px; height: 30px; border-radius: 50%; margin-right: 8px;">
                            {% endif %}
                            {{ user.username }}
                        </a>

                        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="{% url 'core:edit_profile' %}">Editar Perfil</a></li>

                            {% if user.is_superuser %}
                            <li>
                                <a class="dropdown-item {% if request.path == "/mascota/crear/" %} active {% endif %}" href="{% url 'mascota:mascota_create'%}">Cargar mascota</a>
                            </li>
                            
                            {% endif %}
                            <li>
                                <form action="{% url 'core:logout' %}" method="post">
                                    {% csrf_token %}
                                    <button type="submit" class="dropdown-item">Cerrar Sesion</button>
                                </form>
                            </li>
                            
                        </ul>
                    </li>
                {% else %}
                    <li class="nav-item"><a class="nav-link {% if request.path == "/login/" %} active {% endif %}" href="{% url 'core:login' %}">Login</a></li>
                    <li class="nav-item"><a class="nav-link {% if request.path == "/register/" %} active {% endif %}" href="{% url 'core:register' %}">Registrarse</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

core/templates/core/components/titulo1.html
<div class="row align-items-center my-2">
    <h1 class="pb-lg-2 text-white bg-custom-color px-3 py- rounded">
        {{ titulo }}
    </h1>
</div>